//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democratics
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbb8e2ff3f72c74b72880ca18a014fe9baEntities3 : DbContext
    {
        public dbb8e2ff3f72c74b72880ca18a014fe9baEntities3()
            : base("name=dbb8e2ff3f72c74b72880ca18a014fe9baEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserDevice> UserDevices { get; set; }
        public DbSet<UserInfo> UserInfoes { get; set; }
        public DbSet<UserKarma> UserKarmas { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
