//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democratics
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string meno { get; set; }
        public int p_meno { get; set; }
        public string priezvisko { get; set; }
        public int p_priezvisko { get; set; }
        public string email { get; set; }
        public int p_email { get; set; }
    }
}
